[centos]
centos01 ansible_host=10.0.2.4 ansible_user=sysadmin
#centos02 ansible_host=10.0.2.4

[ubuntu]
ubuntu01 ansible_host=10.0.2.5 ansible_user=sysadmin
#ubuntu02 ansible_host=10.0.2.3

[linux:children]
centos
ubuntu






